app_env: dev
mode: local
log_level: debug
database:
  host: db
  port: 5432
  user: postgres
  password: password
  db: tiktok
SECRET_KEY: "BMUJVZQZUClKl1RYbD9pcrO-Dcaby0DTjr8FdmJdhxI"
ACCESS_TOKEN_EXPIRE_MINUTES: 30
ALGORITHM: "HS256"
bucket_name: tiktok-videos
endpoint: http://minio:9000
access_key: minioadmin
secret_key: minioadmin