version: "3"
services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: local
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: >
      uvicorn tik_tok.main:app --host 0.0.0.0 --port 3000 --reload