"""Make thumbnail_url nullable

Revision ID: 81984fc3996a
Revises: 51cf2b3fb50a
Create Date: 2024-12-31 18:19:58.143526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81984fc3996a'
down_revision: Union[str, None] = '51cf2b3fb50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
